### PR TITLE
qmk_firmware

### PR DESCRIPTION
**Pull request by rahul0705**
This is the initial docker image for qmk_firmware. Is there a way to test this before the PR is accepted?

### CODE REVIEW

**Comment by AlexTugarev** [comment]
❤️ `r/mk`

---

Hi @rahul0705! 

Thanks for that PR, I was thinking of something similar :-)

I think the easies way to test and polish the config is to create a fork of qmk_firmware into your account and push the `.gitpod.yml`&`Dockerfile`. When you start a Gitpod workspace for your fork it will be picked up.

**Comment by 32leaves** [comment]
@rahul0705 this is really cool. Out of interest: how do you flash the firmware to the MCU? Do you download the `.bin`/`.hex` file and flash it locally?

**Comment by AlexTugarev** [comment]
@32leaves, some MCUs have a mass storage bootloader, but there is also the option to use a DFU boot loader. With the first one it's quite easy to just `rm` && `cp` the `.bin` file.

**Comment by rahul0705** [comment]
@AlexTugarev I've did what you suggested and I was able to run make and it was successful for the most part (some keymaps I think are broken in general).

**Pull request merged**
