### PR TITLE
Add Firefox (mozilla/gecko-dev)

### PR DESCRIPTION
**Pull request by jankeromnes**
In this pull request, I attempt to support Firefox development (using the official Git mirror https://github.com/mozilla/gecko-dev).

The exposed ports come from the Docker image [janitortechnology/firefox](https://github.com/JanitorTechnology/dockerfiles/blob/master/firefox/firefox-git.dockerfile) (which is based on [janitortechnology/ubuntu-dev](https://github.com/JanitorTechnology/dockerfiles/blob/master/ubuntu-dev/ubuntu-dev.dockerfile)):
- `8088`: noVNC port (for a graphical X environment to run and test `firefox` in)
- `8089`: the Cloud9 web IDE (may not be necessary with gitpod since you already have Theia)
- `8090`: the Theia web IDE (same)

Note: The image already includes a Git checkout of Firefox at `/home/user/firefox`, and it's even already pre-compiled. But maybe it can be overwritten by gitpod with a fresh clone (e.g. to check out a particular branch or commit).

I haven't been able to test this configuration file. Please advise on how to do that. (I've tested gitpod on `mozilla/gecko-dev` directly, but wasn't able to build Firefox, because gitpod's default image is missing some packages, and trying to install them via `./mach bootstrap` didn't work because I can't `sudo`).

### CODE REVIEW

**Comment by svenefftinge** [comment]
Using a checkout location outside `/workspace` is a bad idea and actually a bug on our side that it is possible, because changes there will not be stored. So in case you workspace stops, you will loose your work.
We will soon allow shallow clones, to speed up the process.

**Comment by jankeromnes** [comment]
@svenefftinge thank you for merging! When will this new configuration go live?

Also, how is the link established between this file and the https://github.com/mozilla/gecko-dev repository?

**Comment by jankeromnes** [comment]
I just tried using Gitpod on https://github.com/mozilla/gecko-dev/, but it's still the old Docker image being used (i.e. I'm not able to configure or build Firefox).

**Comment by svenefftinge** [comment]
It works immediately, but the folder name has to match the repo name. I renamed it, but I cannot start the workspace. Did you test the image with gitpod?

**Comment by jankeromnes** [comment]
I didn't know how to test it, see original message:

> I haven't been able to test this configuration file. Please advise on how to do that.

I'll try again now that it's set up properly.

**Pull request merged**
